// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmKASwNnQpCESjyGHHx49eEqdg-5Byx1E',
    appId: '1:735190352085:web:80d8a6cbe0c261b63de25c',
    messagingSenderId: '735190352085',
    projectId: 'easy-earn-app-2b7fe',
    authDomain: 'easy-earn-app-2b7fe.firebaseapp.com',
    storageBucket: 'easy-earn-app-2b7fe.appspot.com',
    measurementId: 'G-ZFJRE5E5V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBjbvD_no2NeB2iuFEZGly9uddgozSb0',
    appId: '1:735190352085:android:456ee53531f9465a3de25c',
    messagingSenderId: '735190352085',
    projectId: 'easy-earn-app-2b7fe',
    storageBucket: 'easy-earn-app-2b7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6w76FuTvWqdHC5Fyfpddg73d94cCDdg',
    appId: '1:735190352085:ios:8530cb8d26a98e593de25c',
    messagingSenderId: '735190352085',
    projectId: 'easy-earn-app-2b7fe',
    storageBucket: 'easy-earn-app-2b7fe.appspot.com',
    iosBundleId: 'com.example.easyEarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB6w76FuTvWqdHC5Fyfpddg73d94cCDdg',
    appId: '1:735190352085:ios:5f6ffaca86f6ef483de25c',
    messagingSenderId: '735190352085',
    projectId: 'easy-earn-app-2b7fe',
    storageBucket: 'easy-earn-app-2b7fe.appspot.com',
    iosBundleId: 'com.example.easyEarn.RunnerTests',
  );
}
